[tools]
python = "3.14"
watchexec = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.fmt]
description = "Format the code base"
run = "isort . && black ."

[tasks.setup]
description = "Install Dependencies"
run = "mise install && && pip install -r requirements.txt"

[tasks.serve]
description = "Run the server"
run = "python -m pyredis.main"

[tasks.dev]
description = "Start the server in watch mode"
run = "watchexec -r -e py -- python -m pyredis.main"

[tasks.benchmark]
description = "Run redis benchmark"
run = "redis-benchmark -t set,get -n 10000 -q"
